### ISSUE TITLE
reaction wheel data dependency

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#21]
There is some funny "input data dependency" error that shows up when you connect the rwa_rpm signal in the command generation library.

**Comment by c0lem3** [comment]
The use of a "memory" block can solve this issue at least temporarily. The issue arises when a variable is in a loop of "instantaneous" function/blocks/etc. 
Simulink can't figure out where it begins and ends. Since all paths are "instantaneously" computed, it sees no difference between the output and the fed back signal. This sounds like an initialization issue, but it is being initialized, so I'm unsure what else to do but use a memory block.
