### ISSUE TITLE
magneticDesaturation Controller

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#34]
Since I can't comment on binary files through git, I'll ask my questions here. Sorry for abusing Issues.

1. You're multiplying inertia by RPM right after input 1, are you sure the units line up? RPM is not an SI unit, so momentum won't be in N-s.
2. You're dividing by ||B||^2. Are you sure that B is not initialized to zero anywhere upstream of this controller? Rate transitions, unit delays, etc, can all introduce zero-initial-conditions that will lead to div/0 here. These can be hard bugs to sniff out if we're not careful.  
3. What am I looking at in the unit test? It seems like it's the full sim, and the actuator signal is not scoped, so nothing is plotted when it gets run. We should be able to come up with a simple orbit/mag field/controller/actuator sim that only uses a few libraries to unit test this controller. It's okay if some simplifying assumptions are made in order to show the essence of how the controller works, and then plug it into a full sim.

**Comment by c0lem3** [comment]
1) Yea I know that's kinda weird, but what's being done is specifying a momentum target. I talk about this in the icd too, but it's much much more intuitive to think about the angular momentum of the rwa in terms of the rpm not the radps value. for example, off the top of your head, what should the momentum target be if we want to desat to a value of 2000 rpm be instead of 1000 rpm? For this reason ive made note a few times in the inits and icd that these are not SI units, but they do match up in the code. The simple fact that this is even being asked however leads me to think I should just bite the bullet and switch it all over now. 

2) short answer, yes we need a div by 0 protection on this. I had my code running, it's all good, but maybe the real mag sensors will default to sending 0s or something if they go out. I'll add that in tomorrow or tonight.

3) yea I actually just use main_sim to test this system, but I've now made a formal unit test for it that is not broken. For this unit test, you should run it then hit signal analyzer. I've logged only the most relevant signals (though it does not allow me to rename them to something more readable :,(     ).  I've added a description in the test, but i'll copy and paste it below this. 
I'll argue that not much can actually be taken out of this sim though. Surely, we need both the RWA, MTQ and Dynamics, so we then need env to feed dynamics. We also need almost all of the FSW. there is mode switching, changing objectives, actuator measurements, and sensor measurements that all feed this analysis. For this reason, only the sensor block can be removed, as for now, i can just take our estimated env data as truth.

**Comment by c0lem3** [comment]
Run and click simulation data inspector to see the RPM of the wheels, and the states of the spacecraft. Notice that the wheels do go from saturated to our nominal values of +- 1000RPM, and the sc bus maintains stability (small angular rates) throughout the entire test. The wheel RPMs and the body rates spike after the wheels are desaturated bc the sc then switches to change its orientation as it has not been able to track its desired attitude through this time. Surely, this could be problematic if the new pointing target is far away from the current attitude, you may spend lots of time desatting the wheels just to make a large adjustment right after.

**Comment by tpreynolds** [comment]
1. You can still specify the target in RPM .. but then just do a conversion in the code right before it gets used for calculation. I am hesitant to mix up units like this. Spacecraft are lost on unit conversions (there's a crater on Mars due to it).

I'll check out the unit test.

**Comment by c0lem3** [comment]
Sweet! I added that last night just to try and avoid confusion. In the init, it's specified as an rpm target, but converted in the code. I went back through the code and realized somebody at a code review would think they got us so I said hell nah
