### ISSUE TITLE
State transitions

### ISSUE THREAD

**Issue by c0lem3** [AA-CubeSat-Team/soci-gnc#61]
One thing that has plagued my conscious is wondering whether or not state transition triggers are good enough as digital hysteresis. One example would be transitioning into detumble mode after seeing that the body rates are above 9deg/s. For FSW testing purposes, yes it is because code does not have "faulty" measurements unless you tell it to or it's bugged. As our code stands state transitions are hysteresis checks. So one iteration of the body rate signal reading >9deg/s will switch modes for example. Real sensors will inevitably have some faults and noise. Noise itself will probably not contribute to this issue, but I'm not a sensor expert. What if every one in ten thousand measurements is just wildy incorrect for some reason? Then we will be switching modes when we shouldnt.

After doing some reading into what others have done, I suggest we use temporal logic as a first pass here. I think this will be the easiest to implement. All that is is to say, if this value is above the threshold for at least 0.3 seconds, then we trigger the hysteresis. I actually have two counts of temporal logic already in FSW. This way, one faulty reading is not enough to trigger something drastic on the SC.

I'll also just say this might be easier than checking for n bad measurements in a row for example, but that is also an option for sensors at least.

**Comment by tpreynolds** [comment]
We are only using the angular rate signal filtered by the MEKF to make this decision, and if not, we'll output a simple LPF of the raw measurement. I think this should take care of any instantaneous blips in the measurement, but will test that. This does happen, sensors can have random spikes in their reading caused by who knows what, and if not taken care of properly will affect downstream functions. I think we're safe with respect to our gyro readings tho in this case.
